# Generated by Django 4.2.5 on 2023-09-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=128)),
                ('club_country', models.CharField(max_length=128)),
                ('club_logo', models.ImageField(upload_to='club_logos/')),
                ('club_desc', models.TextField()),
                ('club_manager', models.TextField(max_length=128)),
                ('networth', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=64)),
                ('football_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='FootballApp.footballclub')),
            ],
        ),
    ]
