# Generated by Django 4.2.5 on 2023-09-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='football_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_squad', to='FootballApp.footballclub'),
        ),
    ]
