# Generated by Django 4.2.5 on 2023-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0005_alter_footballclub_club_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='club_manager',
            field=models.CharField(max_length=128),
        ),
    ]
