# Generated by Django 4.2.5 on 2023-09-26 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0006_alter_footballclub_club_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
