# Generated by Django 4.2.5 on 2023-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0007_footballclub_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_img',
            field=models.ImageField(null=True, upload_to='players/'),
        ),
    ]
