# Generated by Django 4.2.5 on 2023-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp', '0008_player_player_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
